# Generated by Django 6.0.3 on 2026-05-26 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Local Customer'), ('retailer', 'Retailer'), ('wholesaler', 'Wholesaler')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('business', models.CharField(blank=True, max_length=150, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='products/')),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Grains', 'Grains'), ('Dairy', 'Dairy')], max_length=50)),
                ('variety', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('normal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bulk_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('call', models.BooleanField(default=False)),
                ('whatsapp', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='farmconnect.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(choices=[('kg', 'Kg'), ('quintal', 'Quintal')], max_length=20)),
                ('payment', models.CharField(choices=[('COD', 'Cash On Delivery'), ('UPI', 'UPI')], max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='farmconnect.farmerproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='farmconnect.user')),
            ],
        ),
    ]
