# Generated by Django 6.0.3 on 2026-05-27 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmconnect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='password',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Password must contain uppercase, lowercase, number and special character', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&]).{8,}$')]),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter valid Indian phone number', regex='^[6-9]\\d{9}$')]),
        ),
    ]
