# Generated by Django 6.0.3 on 2026-05-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmconnect', '0002_alter_farmer_password_alter_farmer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerproduct',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
    ]
