# Generated by Django 6.0.3 on 2026-05-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmconnect', '0003_alter_farmerproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerproduct',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
