# Generated by Django 6.0.3 on 2026-06-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmconnect', '0004_alter_farmerproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerproduct',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kg'), ('quintal', 'Quintal'), ('ton', 'Ton'), ('liter', 'Liter'), ('dozen', 'Dozen')], default='kg', max_length=20),
        ),
    ]
