# Generated by Django 6.0.3 on 2026-06-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmconnect', '0005_farmerproduct_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerproduct',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kg'), ('quintal', 'Quintal'), ('ton', 'Ton'), ('liter', 'Liter'), ('dozen', 'Dozen')], max_length=20),
        ),
    ]
