# Generated by Django 6.0.3 on 2026-06-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmconnect', '0006_alter_farmerproduct_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
